<section class="content">
  <div class="box box-default">
    <!-- /.box-header -->
    <div class="box-body">
      <div class="pull-right"></div>
    </div>
    <!-- /.box-body -->
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-3 form-group">
          <label><?= __lang('From Date'); ?></label>
          <input type="date" id="txtfromdate" name="txtfromdate" class="form-control" autocomplete="off">
        </div>
        <div class="col-md-3 form-group">
          <label><?= __lang('To Date'); ?></label>
          <input type="date" id="txttodate" name="txttodate" class="form-control" autocomplete="off">
        </div>
        <div class="form-group col-md-3">
          <label><?= __lang('Sub-Zone'); ?></label>
            <select class="form-control subzone" id="optzone" name="optzone">
            <option value="">Select</option>
            <?php foreach ($subzone as $key) { ?>
              <option value="<?= $key->zone_code; ?>"><?= $key->zone; ?></option>
            <?php } ?>
            </select>
        </div>
        <div class="form-group col-md-3">
          <label><?= __lang('City'); ?></label>
          <select class="form-control subcity" id="optcity" name="optcity">
          </select>
        </div>
        <div class="col-md-1 form-group">
          <button type="Submit" id="BtnSearch" class="btn btn-primary form-control" value="Search" onclick="Search();"><?= __lang('Search'); ?></button>
        </div>
      </div>
    </div>
      <hr>
      <div class="row">
        <div class="col-md-12">
          <div class="box-header with-border" style="text-align:center;">
            <h3 class="box-title" style="font-size:25px !important;"><?= __lang('Lead Report'); ?></h3>
          </div>
          <div class="box-header with-border">
            <div class="box-body">
              <table width=100% border=1 id="tableData"  class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th><?= __lang('ID'); ?></th>
                  <th><?= __lang('Company name'); ?></th>
                  <th><?= __lang('supplier'); ?></th>
                  <th><?= __lang('Generated by'); ?></th>
                  <th><?= __lang('sub-zone'); ?></th>
                  <th><?= __lang('city'); ?></th>
                  <th><?= __lang('Date'); ?></th>
                  <!-- <th>Action</th> -->
                  <!-- <th>Expense Type</th> -->
                  <!-- <th>Amount</th> -->
                </tr>
              </thead>
              <!-- <tbody>
              <?php foreach ($expensedetails as $key) { ?>
                <tr>
                  <td><?php echo $key->id;?></td>
                  <td><a href="<?php echo base_url('Test/exp/'.$key->id);?>"><button type="button" class="btn btn-primary">PDF</button></a></td>   
                  <td><?php echo __date_format($key->date,'ddmmyyyy');?></td>
                  <th><?php echo emp_name($key->employee_code);?></th>
                  <td><?php echo $key->type;?></td> 
                  <td><?php echo $key->amount;?></td>
                </tr> 
              <?php } ?>
              </tbody> -->
              <tbody id="table"></tbody>
              </table>  
            </div>       
          </div>
        </div>
        <div class="col-md-12">
          <div class="alert alert-success alert-dismissible" id="alertdelete" style="display:none !important;">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4>Details Deleted succeesfully</h4>
          </div>
        </div>
      </div>
    </div>
  </section>
<!-- /.content -->
<script>
  function formBack(){
    parent.history.back();
    return false;
  }
  
  var fromdate=$("#txtfromdate").val();
  var todate=$("#txttodate").val();
  var optzone=$("#optzone").val();
  var optcity=$("#optcity").val();
  
  function Search(){
    tableData($("#optzone").val(),$("#optcity").val(),$("#txtfromdate").val(),$("#txttodate").val());
  }

  function tableData(optzone,optcity,fromdate,todate){
    $.ajax({
      type:"POST",
      url:"<?php echo base_url('Report/lead_type');?>",
      data:{optzone:optzone,optcity:optcity,fromdate:fromdate,todate:todate},
      
      success:function(data){
        $('#table').html(data); 
      }
    })
  }

  /* City dependent combo */
  $(document).ready(function(){
    $('.subzone').change(function(){
      var sub_code = $(this).val();
      alert(sub_code);
      if(sub_code!="")
      {
        $.post(base_url+"/Admin/sub_city/"+sub_code,function(res){
          res = $.parseJSON(res);
          var html = '<option value="" multiple> --- </option>';
          if(res.status == 200){
            $.each(res.data, function(index, value){
                html += '<option value="'+value.code+'">'+value.city+'</option>';
            });
            $('#optcity').html(html);
          }
        })
      }
    })
})
</script>
 